// ─── LMS Module (Adapted for Teachific) ───────────────────────────────────────
// This file contains all 47 LMS tables adapted for org-level scoping and custom domains.
// Generated by: adapt-lms-schema.mjs

import {
  boolean,
  decimal,
  int,
  json,
  longtext,
  mysqlEnum,
  mysqlTable,
  text,
  timestamp,
  varchar,
  bigint,
  uniqueIndex,
} from "drizzle-orm/mysql-core";

export const lmsSections = mysqlTable("lms_sections", {
  orgId: int("orgId").notNull(),
  id: int("id").autoincrement().primaryKey(),
  courseId: int("course_id").notNull(),
  title: varchar("title", { length: 255 }).notNull(),
  position: int("position").default(0).notNull(),
  isPreview: boolean("is_preview").default(false).notNull(),
  dripDays: int("drip_days").default(0).notNull(), // days after enrollment to unlock the whole section
  createdAt: timestamp("created_at").defaultNow().notNull(),
});
export type LmsSection = typeof lmsSections.$inferSelect;


export const lmsLessons = mysqlTable("lms_lessons", {
  id: int("id").autoincrement().primaryKey(),
  courseId: int("course_id"), // direct course reference (sectionId optional for top-level lessons)
  sectionId: int("section_id"), // nullable — top-level lessons have no section
  title: varchar("title", { length: 255 }).notNull(),
  type: mysqlEnum("type", ["video", "text", "quiz", "download", "embed", "video_text"]).default("text").notNull(),
  content: longtext("content"), // rich text HTML or markdown
  videoContent: longtext("video_content"), // rich text below the video for video_text lessons
  embedUrl: varchar("embed_url", { length: 500 }), // iframe src for embed lessons
  mediaAssetId: int("media_asset_id"), // FK to mediaAssets
  position: int("position").default(0).notNull(),
  isPreview: boolean("is_preview").default(false).notNull(), // kept for backward compat; derived from previewMode
  // Three-state preview mode:
  //   'none'                        = enrolled users only (default)
  //   'preview'                     = free preview, always visible to non-enrolled users
  //   'preview_hide_after_purchase' = free preview for non-enrolled, hidden once user purchases
  previewMode: mysqlEnum("preview_mode", ["none", "preview", "preview_hide_after_purchase"]).default("none").notNull(),
  dripDays: int("drip_days").default(0).notNull(), // days after enrollment to unlock
  durationMinutes: int("duration_minutes"),
  requireVideoCompletion: int("require_video_completion").default(0).notNull(), // 1 = must watch video before marking complete
  // null = inherit from course default, 0 = hide, 1 = show
  requireManualComplete: int("require_manual_complete"), // null = inherit from course (default)
  // Lesson Effects
  effectEnabled: boolean("effect_enabled").default(false),
  effectTrigger: varchar("effect_trigger", { length: 20 }).default("lesson_start"),
  effectBannerText: varchar("effect_banner_text", { length: 500 }),
  effectBannerBgColor: varchar("effect_banner_bg_color", { length: 20 }),
  effectBannerTextColor: varchar("effect_banner_text_color", { length: 20 }),
  effectSound: varchar("effect_sound", { length: 50 }),
  effectSoundUrl: varchar("effect_sound_url", { length: 500 }),
  effectConfetti: boolean("effect_confetti").default(false),
  effectConfettiColors: varchar("effect_confetti_colors", { length: 500 }),
  // Confetti mode: 'fall' = gentle falling confetti, 'cannon' = burst from sides
  effectConfettiMode: mysqlEnum("effect_confetti_mode", ["fall", "cannon"]).default("fall"),
  // Banner display duration in seconds (default 5)
  effectBannerDuration: int("effect_banner_duration").default(5),
  // Page builder blocks for rich lesson content (JSON array of Block objects)
  contentBlocks: longtext("content_blocks"),
  // Lesson learning objectives shown in "In This Lesson" panel (JSON array of strings)
  learningObjectives: longtext("learning_objectives"),
  // Override course-level showInstructor: null = inherit from course, true = always show, false = always hide
  showInstructor: mysqlEnum("show_instructor", ["inherit", "show", "hide"]).default("inherit").notNull(),
  // Prerequisite gate: when true, this lesson acts as a gate — all subsequent lessons in the course
  // are locked until this lesson is completed (or at minimum opened, if no Mark Complete button).
  isPrerequisite: boolean("is_prerequisite").default(false).notNull(),
  // Legacy: kept for DB compatibility but no longer used in logic
  prerequisiteLessonId: int("prerequisite_lesson_id"),
  // Live meeting link (Zoom/Teams) — shown as "Join Live" button on enrolled course overview only
  meetingLink: varchar("meeting_link", { length: 1024 }),
  // Scheduled start/end times for the live session (UTC ms). Join Live button appears 15 min before
  // liveStartAt and hides after liveEndAt (or 3 hours after liveStartAt if liveEndAt is not set).
  liveStartAt: bigint("live_start_at", { mode: "number" }),
  liveEndAt: bigint("live_end_at", { mode: "number" }),
  // Comments: when true, enrolled students can post comments on this lesson
  commentsEnabled: boolean("comments_enabled").default(false).notNull(),
  // Per-lesson publish status: 'published' = visible to enrolled learners (default), 'draft' = hidden from learners even if course is published
  lessonStatus: mysqlEnum("lesson_status", ["published", "draft"]).default("published").notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().onUpdateNow().notNull(),
});
export type LmsLesson = typeof lmsLessons.$inferSelect;

// ── Section Templates ─────────────────────────────────────────────────────────
// A section template stores a section title + all its lessons (as a JSON snapshot)
// so admins can reuse common module structures across courses.

export const lmsSectionTemplates = mysqlTable("lms_section_templates", {
  id: int("id").autoincrement().primaryKey(),
  name: varchar("name", { length: 255 }).notNull(), // template display name
  description: text("description"), // optional description
  sectionTitle: varchar("section_title", { length: 255 }).notNull(), // default section title when imported
  // JSON snapshot of lessons: array of { title, type, content, embedUrl, dripDays, requireVideoCompletion, requireManualComplete, durationMinutes, contentBlocks, learningObjectives }
  lessonsJson: longtext("lessons_json").notNull(),
  lessonCount: int("lesson_count").default(0).notNull(),
  createdByUserId: int("created_by_user_id").notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().onUpdateNow().notNull(),
});
export type LmsSectionTemplate = typeof lmsSectionTemplates.$inferSelect;


export const lmsQuizzes = mysqlTable("lms_quizzes", {
  id: int("id").autoincrement().primaryKey(),
  lessonId: int("lesson_id").notNull().unique(),
  title: varchar("title", { length: 255 }).notNull(),
  passingScore: int("passing_score").default(70).notNull(), // percentage
  allowRetakes: boolean("allow_retakes").default(true).notNull(),
  showCorrectAnswers: boolean("show_correct_answers").default(true).notNull(),
  requirePassingToProgress: boolean("require_passing_to_progress").default(false).notNull(),
  randomizeQuestions: boolean("randomize_questions").default(false).notNull(),
  randomizeAnswers: boolean("randomize_answers").default(false).notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});
export type LmsQuiz = typeof lmsQuizzes.$inferSelect;


export const lmsQuizQuestions = mysqlTable("lms_quiz_questions", {
  id: int("id").autoincrement().primaryKey(),
  quizId: int("quiz_id").notNull(),
  question: text("question").notNull(),
  type: mysqlEnum("type", ["mcq", "truefalse"]).default("mcq").notNull(),
  options: text("options"), // JSON array of strings
  correctAnswer: varchar("correct_answer", { length: 255 }).notNull(),
  explanation: text("explanation"),
  position: int("position").default(0).notNull(),
});
export type LmsQuizQuestion = typeof lmsQuizQuestions.$inferSelect;


export const lmsEnrollments = mysqlTable("lms_enrollments", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("user_id").notNull(),
  courseId: int("course_id").notNull(),
  enrolledAt: timestamp("enrolled_at").defaultNow().notNull(),
  completedAt: timestamp("completed_at"),
  progressPct: int("progress_pct").default(0).notNull(),
  groupId: int("group_id"),
  affiliateCode: varchar("affiliate_code", { length: 64 }),
  orderId: int("order_id"),
  // Enrollment type: 'full' = paid/full access, 'free_preview' = free preview only (limited to preview lessons)
  enrollmentType: mysqlEnum("enrollment_type", ["full", "free_preview"]).default("full").notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});
export type LmsEnrollment = typeof lmsEnrollments.$inferSelect;


export const lmsLessonProgress = mysqlTable("lms_lesson_progress", {
  id: int("id").autoincrement().primaryKey(),
  enrollmentId: int("enrollment_id").notNull(),
  lessonId: int("lesson_id").notNull(),
  completedAt: timestamp("completed_at"),
  quizScore: int("quiz_score"), // percentage if quiz lesson
  quizPassed: boolean("quiz_passed"),
  attempts: int("attempts").default(0).notNull(),
});
export type LmsLessonProgress = typeof lmsLessonProgress.$inferSelect;


export const lmsGroups = mysqlTable("lms_groups", {
  id: int("id").autoincrement().primaryKey(),
  /** Legacy single-course field — kept for backward compat, new teams use lmsGroupCourses */
  courseId: int("course_id"),
  name: varchar("name", { length: 255 }).notNull(),
  /** Legacy total seats — new teams track seats per course in lmsGroupCourses */
  seats: int("seats").default(1).notNull(),
  managerId: int("manager_id"), // FK to users — the group manager (legacy)
  /** Team admin user ID — has team-admin role, can manage this team only */
  teamAdminId: int("team_admin_id"),
  /** Organisation / institution name */
  orgName: varchar("org_name", { length: 255 }),
  /** Team admin contact email */
  adminEmail: varchar("admin_email", { length: 320 }),
  /** Team admin contact phone */
  adminPhone: varchar("admin_phone", { length: 50 }),
  /** Organisation website */
  website: varchar("website", { length: 255 }),
  notes: text("notes"),
  // Stripe order that created this group (set after webhook fulfillment)
  orderId: int("order_id"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().onUpdateNow().notNull(),
});
export type LmsGroup = typeof lmsGroups.$inferSelect;

/** Per-course seat allocation for a team (replaces single courseId+seats on lmsGroups) */

export const lmsGroupCourses = mysqlTable("lms_group_courses", {
  id: int("id").autoincrement().primaryKey(),
  groupId: int("group_id").notNull(),
  courseId: int("course_id").notNull(),
  seats: int("seats").default(1).notNull(),
  /** Stripe order that added this course allocation */
  orderId: int("order_id"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().onUpdateNow().notNull(),
});
export type LmsGroupCourse = typeof lmsGroupCourses.$inferSelect;


export const lmsGroupSeats = mysqlTable("lms_group_seats", {
  id: int("id").autoincrement().primaryKey(),
  groupId: int("group_id").notNull(),
  email: varchar("email", { length: 320 }).notNull(),
  memberName: varchar("member_name", { length: 255 }), // optional display name
  status: mysqlEnum("status", ["pending", "active", "revoked"]).default("pending").notNull(),
  assignedAt: timestamp("assigned_at").defaultNow().notNull(),
  enrollmentId: int("enrollment_id"), // set when user accepts and enrolls
  inviteToken: varchar("invite_token", { length: 128 }),
  acceptedAt: timestamp("accepted_at"),
  lastInviteSentAt: timestamp("last_invite_sent_at"),
});
export type LmsGroupSeat = typeof lmsGroupSeats.$inferSelect;


export const lmsInstructors = mysqlTable("lms_instructors", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("user_id"), // optional link to app user account
  name: varchar("name", { length: 255 }).notNull(),
  title: varchar("title", { length: 255 }),
  bio: longtext("bio"),
  avatarUrl: text("avatar_url"),
  website: varchar("website", { length: 255 }),
  isActive: boolean("is_active").default(true).notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().onUpdateNow().notNull(),
});
export type LmsInstructor = typeof lmsInstructors.$inferSelect;


export const lmsCourseInstructors = mysqlTable("lms_course_instructors", {
  id: int("id").autoincrement().primaryKey(),
  courseId: int("course_id").notNull(),
  instructorId: int("instructor_id").notNull(),
  revenueSharePct: int("revenue_share_pct").default(0).notNull(), // 0-100
  isPrimary: boolean("is_primary").default(false).notNull(),
});
export type LmsCourseInstructor = typeof lmsCourseInstructors.$inferSelect;


export const lmsAffiliates = mysqlTable("lms_affiliates", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("user_id"), // optional link to app user
  name: varchar("name", { length: 255 }).notNull(),
  email: varchar("email", { length: 320 }),
  code: varchar("code", { length: 64 }).notNull().unique(),
  commissionPct: int("commission_pct").default(10).notNull(), // percentage
  isActive: boolean("is_active").default(true).notNull(),
  totalEarned: int("total_earned").default(0).notNull(), // cents
  totalPaid: int("total_paid").default(0).notNull(), // cents
  createdAt: timestamp("created_at").defaultNow().notNull(),
});
export type LmsAffiliate = typeof lmsAffiliates.$inferSelect;


export const lmsAffiliateConversions = mysqlTable("lms_affiliate_conversions", {
  id: int("id").autoincrement().primaryKey(),
  affiliateId: int("affiliate_id").notNull(),
  enrollmentId: int("enrollment_id"), // nullable for non-LMS conversions (e.g. digital downloads)
  orderId: int("order_id"), // nullable for non-LMS conversions
  digitalPurchaseId: int("digital_purchase_id"), // for digital download conversions
  conversionType: varchar("conversion_type", { length: 32 }).default("lms_course"), // lms_course | digital_download
  saleAmount: int("sale_amount").notNull(), // cents
  commissionAmount: int("commission_amount").notNull(), // cents
  paidAt: timestamp("paid_at"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});
export type LmsAffiliateConversion = typeof lmsAffiliateConversions.$inferSelect;


export const lmsLandingPages = mysqlTable("lms_landing_pages", {
  id: int("id").autoincrement().primaryKey(),
  courseId: int("course_id").notNull().unique(),
  heroTitle: varchar("hero_title", { length: 255 }),
  heroSubtitle: text("hero_subtitle"),
  heroImageUrl: text("hero_image_url"),
  bodyContent: longtext("body_content"), // rich text HTML
  ctaText: varchar("cta_text", { length: 128 }).default("Enroll Now"),
  whatYouLearn: longtext("what_you_learn"), // rich text
  requirements: longtext("requirements"), // rich text
  isCustom: boolean("is_custom").default(false).notNull(),
  blocks: longtext("blocks"), // JSON array of page builder blocks
  seoTitle: varchar("seo_title", { length: 255 }),
  seoDescription: text("seo_description"),
  seoImage: varchar("seo_image", { length: 512 }),
  // Per-funnel publish domain override (null = use global funnelPublishDomain)
  publishDomain: varchar("publish_domain", { length: 255 }),
  updatedAt: timestamp("updated_at").defaultNow().onUpdateNow().notNull(),
});
export type LmsLandingPage = typeof lmsLandingPages.$inferSelect;


export const lmsOrders = mysqlTable("lms_orders", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("user_id").notNull(),
  courseId: int("course_id").notNull(),
  amount: int("amount").notNull(), // cents
  currency: varchar("currency", { length: 8 }).default("usd").notNull(),
  stripePaymentIntentId: varchar("stripe_payment_intent_id", { length: 255 }),
  stripeSessionId: varchar("stripe_session_id", { length: 255 }),
  stripeSubscriptionId: varchar("stripe_subscription_id", { length: 255 }),
  status: mysqlEnum("status", ["pending", "paid", "failed", "refunded"]).default("pending").notNull(),
  affiliateId: int("affiliate_id"),
  groupId: int("group_id"),
  seats: int("seats").default(1).notNull(), // for group purchases
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().onUpdateNow().notNull(),
});
export type LmsOrder = typeof lmsOrders.$inferSelect;

// ─── LMS Page Templates ───────────────────────────────────────────────────────


export const lmsPageTemplates = mysqlTable("lms_page_templates", {
  id: int("id").autoincrement().primaryKey(),
  name: varchar("name", { length: 255 }).notNull(),
  description: text("description"),
  templateType: mysqlEnum("template_type", ["page", "block"]).notNull().default("page"),
  blockType: varchar("block_type", { length: 64 }),
  blocks: longtext("blocks").notNull(), // JSON array of Block objects
  thumbnailUrl: text("thumbnail_url"),
  createdBy: int("created_by"),
  createdAt: bigint("created_at", { mode: "number" }).notNull(),
  updatedAt: bigint("updated_at", { mode: "number" }).notNull(),
});
export type LmsPageTemplate = typeof lmsPageTemplates.$inferSelect;
export type NewLmsPageTemplate = typeof lmsPageTemplates.$inferInsert;

// ─── LMS Certificate Templates ───────────────────────────────────────────────


export const lmsCertificateTemplates = mysqlTable("lms_certificate_templates", {
  id: int("id").autoincrement().primaryKey(),
  name: varchar("name", { length: 200 }).notNull(),
  description: text("description"),
  // Visual design
  backgroundImageUrl: text("background_image_url"),
  logoUrl: text("logo_url"),
  primaryColor: varchar("primary_color", { length: 20 }).default("#189aa1").notNull(),
  accentColor: varchar("accent_color", { length: 20 }).default("#c9a84c").notNull(),
  textColor: varchar("text_color", { length: 20 }).default("#0e1e2e").notNull(),
  fontFamily: varchar("font_family", { length: 100 }).default("Helvetica").notNull(),
  // Signature block
  signatureName: varchar("signature_name", { length: 200 }),
  signatureTitle: varchar("signature_title", { length: 200 }),
  signatureImageUrl: text("signature_image_url"),
  // Footer / legal text
  footerText: text("footer_text"),
  // Organization name shown on the certificate
  organizationName: varchar("organization_name", { length: 200 }).default("All About Ultrasound").notNull(),
  // Layout variant: classic | modern | minimal
  layout: mysqlEnum("layout", ["classic", "modern", "minimal"]).default("classic").notNull(),
  isDefault: boolean("is_default").default(false).notNull(),
  isActive: boolean("is_active").default(true).notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().onUpdateNow().notNull(),
});
export type LmsCertificateTemplate = typeof lmsCertificateTemplates.$inferSelect;
export type InsertLmsCertificateTemplate = typeof lmsCertificateTemplates.$inferInsert;

export const lmsCertificates = mysqlTable("lms_certificates", {
  orgId: int("orgId").notNull(),
  id: int("id").autoincrement().primaryKey(),
  userId: int("user_id").notNull(),
  courseId: int("course_id").notNull(),
  enrollmentId: int("enrollment_id").notNull(),
  certificateUrl: text("certificate_url").notNull(),
  templateId: int("template_id"), // FK to lms_certificate_templates.id (null = legacy/default)
  issuedAt: timestamp("issued_at").defaultNow().notNull(),
});
export type LmsCertificate = typeof lmsCertificates.$inferSelect;

// ─── LMS Lesson Notes ─────────────────────────────────────────────────────────


export const lmsLessonNotes = mysqlTable("lms_lesson_notes", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("user_id").notNull(),
  lessonId: int("lesson_id").notNull(),
  courseId: int("course_id").notNull(),
  note: longtext("note").notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().onUpdateNow().notNull(),
});
export type LmsLessonNote = typeof lmsLessonNotes.$inferSelect;

// ─── LMS Lesson Bookmarks ─────────────────────────────────────────────────────


export const lmsLessonBookmarks = mysqlTable("lms_lesson_bookmarks", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("user_id").notNull(),
  lessonId: int("lesson_id").notNull(),
  courseId: int("course_id").notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});
export type LmsLessonBookmark = typeof lmsLessonBookmarks.$inferSelect;

// ─── LMS Collections ─────────────────────────────────────────────────────────

export const lmsCollections = mysqlTable("lms_collections", {
  id: int("id").autoincrement().primaryKey(),
  title: varchar("title", { length: 200 }).notNull(),
  description: text("description"),
  label: varchar("label", { length: 100 }),
  color: varchar("color", { length: 20 }).default("#189aa1"),
  coverImageUrl: text("cover_image_url"),
  position: int("position").default(0).notNull(),
  isPublished: boolean("is_published").default(true).notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().onUpdateNow().notNull(),
});
export type LmsCollection = typeof lmsCollections.$inferSelect;


export const lmsCollectionCourses = mysqlTable("lms_collection_courses", {
  id: int("id").autoincrement().primaryKey(),
  collectionId: int("collection_id").notNull(),
  courseId: int("course_id").notNull(),
  position: int("position").default(0).notNull(),
});
export type LmsCollectionCourse = typeof lmsCollectionCourses.$inferSelect;


// ─── Digital Downloads (File Repository) ────────────────────────────────────

export const lmsVideoEvents = mysqlTable("lms_video_events", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("user_id").notNull(),
  lessonId: int("lesson_id").notNull(),
  courseId: int("course_id").notNull(),
  eventType: varchar("event_type", { length: 32 }).notNull(), // 'play'|'pause'|'complete'|'seek'|'progress'
  positionSec: int("position_sec").default(0).notNull(),      // playback position
  durationSec: int("duration_sec").default(0).notNull(),      // total video length
  percentWatched: int("percent_watched").default(0).notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});
export type LmsVideoEvent = typeof lmsVideoEvents.$inferSelect;
export type InsertLmsVideoEvent = typeof lmsVideoEvents.$inferInsert;

export const lmsQuizAttempts = mysqlTable("lms_quiz_attempts", {
  orgId: int("orgId").notNull(),
  id: int("id").autoincrement().primaryKey(),
  userId: int("user_id").notNull(),
  lessonId: int("lesson_id").notNull(),
  courseId: int("course_id").notNull(),
  score: int("score").notNull(),          // percentage 0-100
  passed: boolean("passed").notNull(),
  totalQuestions: int("total_questions").notNull(),
  correctAnswers: int("correct_answers").notNull(),
  timeTakenSec: int("time_taken_sec"),
  answersJson: longtext("answers_json"),  // JSON array of {questionId, selectedAnswer, correct}
  createdAt: timestamp("created_at").defaultNow().notNull(),
});
export type LmsQuizAttempt = typeof lmsQuizAttempts.$inferSelect;
export type InsertLmsQuizAttempt = typeof lmsQuizAttempts.$inferInsert;

export const lessonTemplates = mysqlTable("lesson_templates", {
  orgId: int("orgId").notNull(),
  id: int("id").autoincrement().primaryKey(),
  title: varchar("title", { length: 255 }).notNull(),
  lessonType: varchar("lesson_type", { length: 64 }).default("video").notNull(),
  blocks: longtext("blocks"),
  coverImage: text("cover_image"),
  tags: text("tags"),
  createdByAdminId: int("created_by_admin_id"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().onUpdateNow().notNull(),
});
export type LessonTemplate = typeof lessonTemplates.$inferSelect;

// ─── Question Bank ─────────────────────────────────────────────────────────────
// Central repository of reusable quiz questions with tagging support.
// Questions are auto-saved here when created via the quiz builder or AI generator.
// Media: questionImageUrl / questionVideoUrl attach to the question stem.
// Options are stored as JSON array of objects: { text, imageUrl?, videoUrl? }
// Quiz-level settings (randomizeQuestions, randomizeAnswers) live on lms_quizzes.


export const lmsCohortSessions = mysqlTable("lms_cohort_sessions", {
  id: int("id").autoincrement().primaryKey(),
  courseId: int("course_id").notNull(),
  title: varchar("title", { length: 255 }).notNull(),
  description: text("description"),
  sessionDate: timestamp("session_date").notNull(),
  durationMinutes: int("duration_minutes").default(60).notNull(),
  meetingUrl: text("meeting_url"),
  recordingUrl: text("recording_url"),
  // draft = not yet visible to students; published = visible; cancelled = cancelled
  status: mysqlEnum("status", ["draft", "published", "cancelled"]).default("draft").notNull(),
  // IANA timezone string for this session (e.g. "America/New_York", "Europe/London")
  timezone: varchar("timezone", { length: 64 }).default("America/New_York"),
  // ── Recurrence ──────────────────────────────────────────────────────────────
  // recurrenceRule: weekly | biweekly | monthly | null (one-off)
  recurrenceRule: mysqlEnum("recurrence_rule", ["weekly", "biweekly", "monthly"]),
  // Comma-separated days of week for custom recurrence: "0,1,2,3,4,5,6" (0=Sun)
  recurrenceDaysOfWeek: varchar("recurrence_days_of_week", { length: 20 }),
  recurrenceInterval: int("recurrence_interval").default(1), // multiplier (reserved for future use)
  recurrenceEndDate: timestamp("recurrence_end_date"),       // inclusive last occurrence date
  // Alternative to end date: stop after N occurrences
  recurrenceOccurrenceCount: int("recurrence_occurrence_count"),
  // parentSessionId links child instances back to the template/parent session
  parentSessionId: int("parent_session_id"),
  // Cohort group this session belongs to (null = shared across all groups / single-cohort mode)
  cohortGroupId: int("cohort_group_id"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().onUpdateNow().notNull(),
});
export type LmsCohortSession = typeof lmsCohortSessions.$inferSelect;
export type InsertLmsCohortSession = typeof lmsCohortSessions.$inferInsert;

export const lmsCohortRecordings = mysqlTable("lms_cohort_recordings", {
  orgId: int("orgId").notNull(),
  id: int("id").autoincrement().primaryKey(),
  courseId: int("course_id").notNull(),
  sessionId: int("session_id"),           // optional link to a live session
  title: varchar("title", { length: 255 }).notNull(),
  description: text("description"),
  videoUrl: text("video_url"),
  thumbnailUrl: text("thumbnail_url"),
  durationSeconds: int("duration_seconds"),
  status: mysqlEnum("status", ["draft", "published"]).default("draft").notNull(),
  position: int("position").default(0).notNull(),
  // Cohort group this recording belongs to (null = shared / single-cohort mode)
  cohortGroupId: int("cohort_group_id"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().onUpdateNow().notNull(),
});
export type LmsCohortRecording = typeof lmsCohortRecordings.$inferSelect;
export type InsertLmsCohortRecording = typeof lmsCohortRecordings.$inferInsert;

export const lmsCohortGroups = mysqlTable("lms_cohort_groups", {
  orgId: int("orgId").notNull(),
  id: int("id").autoincrement().primaryKey(),
  courseId: int("course_id").notNull(), // FK to lms_courses.id (type = 'cohort')
  name: varchar("name", { length: 255 }).notNull(), // e.g. "June 2026 Cohort"
  slug: varchar("slug", { length: 255 }).notNull(), // URL-safe identifier
  description: text("description"),
  startDate: timestamp("start_date"),
  endDate: timestamp("end_date"),
  enrollmentCloseDate: timestamp("enrollment_close_date"),
  maxStudents: int("max_students"), // null = unlimited
  status: mysqlEnum("status", ["draft", "open", "active", "completed", "archived"]).default("draft").notNull(),
  // Page builder blocks for this specific cohort group's overview page
  pageBlocks: longtext("page_blocks"),
  // Landing page link override — which cohort to feature on the course landing page
  isFeaturedOnLanding: boolean("is_featured_on_landing").default(false).notNull(),
  sortOrder: int("sort_order").default(0).notNull(),
  // How many days students retain access from group start date (null = indefinite)
  accessDurationDays: int("access_duration_days"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().onUpdateNow().notNull(),
});
export type LmsCohortGroup = typeof lmsCohortGroups.$inferSelect;
export type InsertLmsCohortGroup = typeof lmsCohortGroups.$inferInsert;

export const lmsCohortGroupEnrollments = mysqlTable("lms_cohort_group_enrollments", {
  orgId: int("orgId").notNull(),
  id: int("id").autoincrement().primaryKey(),
  cohortGroupId: int("cohort_group_id").notNull(),
  enrollmentId: int("enrollment_id").notNull(), // FK to lms_enrollments.id
  userId: int("user_id").notNull(),
  courseId: int("course_id").notNull(),
  joinedAt: timestamp("joined_at").defaultNow().notNull(),
});
export type LmsCohortGroupEnrollment = typeof lmsCohortGroupEnrollments.$inferSelect;
export type InsertLmsCohortGroupEnrollment = typeof lmsCohortGroupEnrollments.$inferInsert;

export const lmsCohortStaff = mysqlTable("lms_cohort_staff", {
  orgId: int("orgId").notNull(),
  id: int("id").autoincrement().primaryKey(),
  cohortGroupId: int("cohort_group_id").notNull(),
  courseId: int("course_id").notNull(),
  userId: int("user_id").notNull(),
  role: varchar("role", { length: 20 }).notNull().default("moderator"), // 'admin' | 'moderator'
  canManageDiscussions: boolean("can_manage_discussions").default(true).notNull(),
  canAddSessions: boolean("can_add_sessions").default(false).notNull(),
  canAddAssignments: boolean("can_add_assignments").default(false).notNull(),
  canAddRecordings: boolean("can_add_recordings").default(false).notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().onUpdateNow().notNull(),
});
export type LmsCohortStaff = typeof lmsCohortStaff.$inferSelect;
export type InsertLmsCohortStaff = typeof lmsCohortStaff.$inferInsert;

export const lmsInterests = mysqlTable("lms_interests", {
  orgId: int("orgId").notNull(),
  id: int("id").autoincrement().primaryKey(),
  name: varchar("name", { length: 100 }).notNull(),
  slug: varchar("slug", { length: 100 }).notNull(),
  category: varchar("category", { length: 50 }).notNull().default("general"), // 'general' | 'echo' | 'both'
  // brandFilter: 'aaus' = general ultrasound only, 'iheartecho' = echo only, 'both' = all brands
  brandFilter: varchar("brand_filter", { length: 20 }).notNull().default("both"),
  iconEmoji: varchar("icon_emoji", { length: 10 }),
  sortOrder: int("sort_order").notNull().default(0),
  isActive: boolean("is_active").default(true).notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});
export type LmsInterest = typeof lmsInterests.$inferSelect;
export type InsertLmsInterest = typeof lmsInterests.$inferInsert;

export const instructorPublishRequests = mysqlTable("instructor_publish_requests", {
  orgId: int("orgId").notNull(),
  id: int("id").autoincrement().primaryKey(),
  courseId: int("course_id").notNull(),
  instructorId: int("instructor_id").notNull(),
  status: mysqlEnum("status", ["pending", "approved", "rejected"]).default("pending").notNull(),
  note: text("note"),
  reviewNote: text("review_note"),
  reviewedByAdminId: int("reviewed_by_admin_id"),
  requestedAt: timestamp("requested_at").defaultNow().notNull(),
  reviewedAt: timestamp("reviewed_at"),
});
export type InstructorPublishRequest = typeof instructorPublishRequests.$inferSelect;
export type InsertInstructorPublishRequest = typeof instructorPublishRequests.$inferInsert;
